extra:
  analytics:
    property: G-BYVB1ZVE6J
    provider: google
extra_css:
- css/style.css
extra_javascript:
- javascript/llms_example.js
- javascript/mendablesearch.js
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- md_in_html
- toc:
    permalink: '#'
nav:
- Home:
  - LlamaIndex: index.md
  - getting_started/concepts.md
  - getting_started/installation.md
  - getting_started/reading.md
  - Starter Examples:
    - getting_started/starter_example.md
    - getting_started/starter_example_local.md
  - getting_started/discover_llamaindex.md
  - getting_started/customization.md
- Learn:
  - Building an LLM Application: ./understanding/index.md
  - Using LLMs: ./understanding/using_llms/using_llms.md
  - Loading & Ingestion:
    - ./understanding/loading/loading.md
    - ./understanding/loading/llamahub.md
  - Indexing & Embedding: ./understanding/indexing/indexing.md
  - Storing: ./understanding/storing/storing.md
  - Querying: ./understanding/querying/querying.md
  - Tracing and Debugging: ./understanding/tracing_and_debugging/tracing_and_debugging.md
  - Evaluating:
    - ./understanding/evaluating/evaluating.md
    - Cost Analysis:
      - ./understanding/evaluating/cost_analysis/index.md
      - ./understanding/evaluating/cost_analysis/usage_pattern.md
  - Putting it all Together: ./understanding/putting_it_all_together/
- Use Cases:
  - ./use_cases/index.md
  - Agents: ./use_cases/agents.md
  - Chatbots: ./use_cases/chatbots.md
  - Multi-Modal Applications: ./use_cases/multimodal.md
  - Structured Data Extraction: ./use_cases/extraction.md
  - General Q&A: ./use_cases/q_and_a/index.md
  - Fine-Tuning: ./use_cases/fine_tuning.md
- Examples:
  - ./examples/index.md
- Component Guides:
  - ./module_guides/index.md
  - Models:
    - ./module_guides/models/index.md
    - LLMs:
      - ./module_guides/models/llms.md
      - Standalone Usage: ./module_guides/models/llms/usage_standalone.md
      - Customizing LLMs: ./module_guides/models/llms/usage_custom.md
      - Available LLM Integrations: ./module_guides/models/llms/modules.md
    - Embeddings: ./module_guides/models/embeddings.md
    - Multi Modal: ./module_guides/models/multi_modal.md
  - Prompts:
    - ./module_guides/models/prompts/index.md
    - ./module_guides/models/prompts/usage_pattern.md
  - Loading:
    - ./module_guides/loading/index.md
    - Documents and Nodes:
      - ./module_guides/loading/documents_and_nodes/index.md
      - Using Documents: ./module_guides/loading/documents_and_nodes/usage_documents.md
      - Using Nodes: ./module_guides/loading/documents_and_nodes/usage_nodes.md
      - Metadata Extraction: ./module_guides/loading/documents_and_nodes/usage_metadata_extractor.md
    - SimpleDirectoryReader: ./module_guides/loading/simpledirectoryreader.md
    - Data Connectors:
      - ./module_guides/loading/connector/index.md
      - ./module_guides/loading/connector/usage_pattern.md
      - LlamaParse: ./module_guides/loading/connector/llama_parse.md
      - ./module_guides/loading/connector/modules.md
    - Node Parsers / Text Splitters:
      - ./module_guides/loading/node_parsers/index.md
      - ./module_guides/loading/node_parsers/modules.md
    - Ingestion Pipeline:
      - ./module_guides/loading/ingestion_pipeline/index.md
      - ./module_guides/loading/ingestion_pipeline/transformations.md
  - Indexing:
    - ./module_guides/indexing/index.md
    - Index Guide: ./module_guides/indexing/index_guide.md
    - Vector Store Index: ./module_guides/indexing/vector_store_index.md
    - Document Management: ./module_guides/indexing/document_management.md
    - LlamaCloud: ./module_guides/indexing/llama_cloud_index.md
    - Metadata Extraction: ./module_guides/indexing/metadata_extraction.md
    - Modules: ./module_guides/indexing/modules.md
  - Storing:
    - ./module_guides/storing/index.md
    - ./module_guides/storing/vector_stores.md
    - ./module_guides/storing/docstores.md
    - ./module_guides/storing/index_stores.md
    - ./module_guides/storing/chat_stores.md
    - ./module_guides/storing/kv_stores.md
    - ./module_guides/storing/save_load.md
    - ./module_guides/storing/customization.md
  - Querying:
    - ./module_guides/querying/index.md
    - Retrieval:
      - ./module_guides/querying/retriever/index.md
      - ./module_guides/querying/retriever/retrievers.md
      - ./module_guides/querying/retriever/retriever_modes.md
    - Node Postprocessors:
      - ./module_guides/querying/node_postprocessors/index.md
      - ./module_guides/querying/node_postprocessors/node_postprocessors.md
    - Response Synthesis:
      - ./module_guides/querying/response_synthesizers/index.md
      - ./module_guides/querying/response_synthesizers/response_synthesizers.md
    - Routing: ./module_guides/querying/router/index.md
    - Query Pipelines:
      - ./module_guides/querying/pipeline/index.md
      - ./module_guides/querying/pipeline/usage_pattern.md
      - ./module_guides/querying/pipeline/modules.md
      - ./module_guides/querying/pipeline/module_usage.md
    - Structured Outputs:
      - ./module_guides/querying/structured_outputs/index.md
      - ./module_guides/querying/structured_outputs/output_parser.md
      - ./module_guides/querying/structured_outputs/query_engine.md
      - ./module_guides/querying/structured_outputs/pydantic_program.md
  - Evaluation:
    - ./module_guides/evaluating/index.md
    - ./module_guides/evaluating/usage_pattern.md
    - ./module_guides/evaluating/usage_pattern_retrieval.md
    - ./module_guides/evaluating/modules.md
    - LlamaDatasets:
      - ./module_guides/evaluating/contributing_llamadatasets.md
      - ./module_guides/evaluating/evaluating_with_llamadatasets.md
      - ./module_guides/evaluating/evaluating_evaluators_with_llamadatasets.md
  - Observability: ./module_guides/observability/index.md
  - Deploying:
    - Agents:
      - ./module_guides/deploying/agents/index.md
      - ./module_guides/deploying/agents/usage_pattern.md
      - ./module_guides/deploying/agents/agent_runner.md
      - ./module_guides/deploying/agents/modules.md
      - Tools:
        - ./module_guides/deploying/agents/tools/index.md
        - ./module_guides/deploying/agents/tools/usage_pattern.md
        - ./module_guides/deploying/agents/tools/llamahub_tools_guide.md
    - Chat Engines:
      - ./module_guides/deploying/chat_engines/index.md
      - ./module_guides/deploying/chat_engines/usage_pattern.md
      - ./module_guides/deploying/chat_engines/modules.md
    - Query Engines:
      - ./module_guides/deploying/query_engine/index.md
      - ./module_guides/deploying/query_engine/usage_pattern.md
      - ./module_guides/deploying/query_engine/response_modes.md
      - ./module_guides/deploying/query_engine/streaming.md
      - ./module_guides/deploying/query_engine/modules.md
      - ./module_guides/deploying/query_engine/supporting_modules.md
  - Settings: ./module_guides/supporting_modules/settings.md
- Advanced Topics:
  - ./optimizing/production_rag.md
  - ./optimizing/basic_strategies/basic_strategies.md
  - ./optimizing/agentic_strategies/agentic_strategies.md
  - Retrieval:
    - ./optimizing/advanced_retrieval/advanced_retrieval.md
    - ./optimizing/advanced_retrieval/query_transformations.md
  - Evaluation: ./optimizing/evaluation
  - Fine-Tuning: ./optimizing/fine-tuning/fine-tuning.md
  - ./optimizing/custom_modules.md
  - ./optimizing/building_rag_from_scratch.md
- API Reference: ./api_reference
- Open-Source Community:
  - Integrations: ./community/integrations.md
  - Full Stack Projects: ./community/full_stack_projects.md
  - Community FAQ: ./community/faq
  - LlamaPacks: ./community/llama_packs/index.md
  - Contributing:
    - Code: ./CONTRIBUTING.md
    - Docs: ./DOCS_README.md
  - Changelog: ./CHANGELOG.md
  - Upgrading to v0.10.x: ./getting_started/v0_10_0_migration.md
  - Deprecated Terms: ./changes/deprecated_terms.md
plugins:
- search
- include_dir_to_nav
- mkdocs-jupyter:
    execute: false
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_options:
            ignore_init_summary: true
          docstring_style: google
          filters:
          - '!^_'
          - '!^__init__'
          members_order: source
          merge_init_into_class: false
          separate_signature: true
          show_root_full_path: true
          show_root_heading: false
          show_root_toc_entry: false
          show_signature_annotations: true
          signature_crossrefs: true
        paths:
        - ../llama-index-core
site_name: LlamaIndex
theme:
  favicon: _static/assets/LlamaLogoBrowserTab.png
  features:
  - navigation.instant
  - navigation.tabs
  - navigation.indexes
  - navigation.top
  - navigation.footer
  - toc.follow
  logo: _static/assets/LlamaSquareBlack.svg
  name: material
  palette:
  - media: (prefers-color-scheme)
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - accent: purple
    media: '(prefers-color-scheme: light)'
    primary: white
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - accent: purple
    media: '(prefers-color-scheme: dark)'
    primary: black
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
